name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: test ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Setup Python 3.9 (Windows)
        uses: actions/setup-python@v2
        if: ${{ matrix.os == 'windows-latest' }}
        with:
          python-version: "3.9"

      - name: Install NumPy
        run: python3 -m pip install numpy

      - name: Run tests
        run: deno test --allow-all --unstable
